// Mock data for the Bookings Management page.
// Swap this out for a real API/store later — the component only
// expects the same shapes (stats fields + bookings array).

export const stats = {
  totalBookings: { value: "1,284" },
  checkInsToday: { value: 42 },
  occupancyRate: { value: 88 },
  revenue: { value: "$124.5k", period: "MTD" },
};

export const bookings = [
  {
    id: "GP-883921",
    name: "Sarah Miller",
    email: "sarah.m@example.com",
    roomType: "Deluxe King Suite",
    roomNumber: "Room 402",
    bookingId: "GP-883921",
    checkIn: "Oct 12",
    checkOut: "Oct 15",
    nights: 3,
    status: "Confirmed",
  },
  {
    id: "GP-901221",
    name: "James Donovan",
    email: "james@donovan.org",
    roomType: "Standard Double",
    roomNumber: "Room 105",
    bookingId: "GP-901221",
    checkIn: "Oct 12",
    checkOut: "Oct 14",
    nights: 2,
    status: "Checked-in",
  },
  {
    id: "GP-992110",
    name: "Emma Watson",
    email: "emma.w@mail.com",
    roomType: "Ocean View Loft",
    roomNumber: "Room 508",
    bookingId: "GP-992110",
    checkIn: "Oct 13",
    checkOut: "Oct 20",
    nights: 7,
    status: "Confirmed",
  },
  {
    id: "GP-872215",
    name: "Robert Brown",
    email: "rbrown@tech.com",
    roomType: "Junior Suite",
    roomNumber: "Unassigned",
    bookingId: "GP-872215",
    checkIn: "Oct 15",
    checkOut: "Oct 17",
    nights: 2,
    status: "Canceled",
  },
  {
    id: "GP-913340",
    name: "Olivia Chen",
    email: "olivia.chen@mail.com",
    roomType: "Deluxe King Suite",
    roomNumber: "Room 410",
    bookingId: "GP-913340",
    checkIn: "Oct 16",
    checkOut: "Oct 19",
    nights: 3,
    status: "Confirmed",
  },
  {
    id: "GP-927741",
    name: "Marcus Webb",
    email: "marcus.w@example.com",
    roomType: "Standard Double",
    roomNumber: "Room 110",
    bookingId: "GP-927741",
    checkIn: "Oct 16",
    checkOut: "Oct 18",
    nights: 2,
    status: "Checked-in",
  },
  {
    id: "GP-938102",
    name: "Priya Patel",
    email: "priya.patel@mail.com",
    roomType: "Ocean View Loft",
    roomNumber: "Room 512",
    bookingId: "GP-938102",
    checkIn: "Oct 17",
    checkOut: "Oct 22",
    nights: 5,
    status: "Confirmed",
  },
  {
    id: "GP-944519",
    name: "Daniel Kim",
    email: "daniel.kim@tech.com",
    roomType: "Junior Suite",
    roomNumber: "Room 301",
    bookingId: "GP-944519",
    checkIn: "Oct 18",
    checkOut: "Oct 19",
    nights: 1,
    status: "Canceled",
  },
  {
    id: "GP-955823",
    name: "Laura Schmidt",
    email: "laura.s@example.com",
    roomType: "Deluxe King Suite",
    roomNumber: "Room 405",
    bookingId: "GP-955823",
    checkIn: "Oct 19",
    checkOut: "Oct 23",
    nights: 4,
    status: "Confirmed",
  },
  {
    id: "GP-961207",
    name: "Tyler Brooks",
    email: "tyler.brooks@mail.com",
    roomType: "Standard Double",
    roomNumber: "Room 108",
    bookingId: "GP-961207",
    checkIn: "Oct 20",
    checkOut: "Oct 21",
    nights: 1,
    status: "Checked-in",
  },
  {
    id: "GP-970456",
    name: "Hannah Lee",
    email: "hannah.lee@mail.com",
    roomType: "Ocean View Loft",
    roomNumber: "Room 515",
    bookingId: "GP-970456",
    checkIn: "Oct 21",
    checkOut: "Oct 28",
    nights: 7,
    status: "Confirmed",
  },
  {
    id: "GP-982390",
    name: "Carlos Mendes",
    email: "carlos.mendes@example.com",
    roomType: "Junior Suite",
    roomNumber: "Room 305",
    bookingId: "GP-982390",
    checkIn: "Oct 22",
    checkOut: "Oct 24",
    nights: 2,
    status: "Confirmed",
  },
];

export const statusFilters = ["All Status", "Confirmed", "Checked-in", "Canceled"];