// Mock data for the Guest Directory page.
// Swap this out for a real API/store later — the component only
// expects the same shapes (stats fields + guests array).

export const stats = {
  vipGuests: { value: 148, badge: "+12% from last month" },
  returningRate: { value: "42.8%", badge: "Consistent growth" },
  avgLifetimeValue: { value: "$2,410", badge: "High value" },
  blacklisted: { value: 14, badge: "Needs review" },
};

export const filters = ["All Guests", "VIP Only", "Corporate", "New (7 Days)"];

export const guests = [
  {
    id: "g1",
    name: "Eleanor Vance",
    email: "eleanor.vance@techcorp.com",
    avatar: "https://i.pravatar.cc/100?img=47",
    status: "Checked In",
    loyalty: "Diamond Elite",
    loyaltyProgress: 80,
    lastVisit: "Oct 12, 2023",
    totalSpent: "$12,450",
  },
  {
    id: "g2",
    name: "Arthur Sterling",
    email: "a.sterling@private.com",
    avatar: "https://i.pravatar.cc/100?img=14",
    status: "Past Guest",
    loyalty: "Platinum",
    lastVisit: "Aug 05, 2023",
    totalSpent: "$8,120",
  },
  {
    id: "g3",
    name: "Jordan Wei",
    email: "jordan.wei@design.io",
    avatar: "https://i.pravatar.cc/100?img=68",
    status: "Reserved",
    loyalty: "Silver",
    lastVisit: "Oct 24, 2023",
    totalSpent: "$1,200",
  },
  {
    id: "g4",
    name: "Sarah Jenkins",
    email: "sjenkins@global-logistics.com",
    avatar: "https://i.pravatar.cc/100?img=32",
    status: "Checked In",
    loyalty: "Diamond Elite",
    loyaltyProgress: 95,
    lastVisit: "Sep 30, 2023",
    totalSpent: "$22,400",
  },
  {
    id: "g5",
    name: "Marcus Hale",
    email: "marcus.hale@example.com",
    avatar: "https://i.pravatar.cc/100?img=22",
    status: "Past Guest",
    loyalty: "Gold",
    lastVisit: "Jul 18, 2023",
    totalSpent: "$5,640",
  },
  {
    id: "g6",
    name: "Priya Anand",
    email: "priya.anand@finco.com",
    avatar: "https://i.pravatar.cc/100?img=45",
    status: "Reserved",
    loyalty: "Platinum",
    lastVisit: "Nov 02, 2023",
    totalSpent: "$9,870",
  },
  {
    id: "g7",
    name: "Tomas Reyes",
    email: "tomas.reyes@mail.com",
    avatar: "https://i.pravatar.cc/100?img=51",
    status: "Checked In",
    loyalty: "Silver",
    lastVisit: "Nov 10, 2023",
    totalSpent: "$980",
  },
  {
    id: "g8",
    name: "Felicity Ahn",
    email: "felicity.ahn@studio.com",
    avatar: "https://i.pravatar.cc/100?img=29",
    status: "Past Guest",
    loyalty: "Diamond Elite",
    loyaltyProgress: 60,
    lastVisit: "Jun 21, 2023",
    totalSpent: "$15,300",
  },
  {
    id: "g9",
    name: "Daniel Obi",
    email: "daniel.obi@example.org",
    avatar: "https://i.pravatar.cc/100?img=60",
    status: "Reserved",
    loyalty: "Gold",
    lastVisit: "Nov 14, 2023",
    totalSpent: "$3,420",
  },
  {
    id: "g10",
    name: "Renata Cruz",
    email: "renata.cruz@globex.com",
    avatar: "https://i.pravatar.cc/100?img=39",
    status: "Checked In",
    loyalty: "Platinum",
    lastVisit: "Nov 16, 2023",
    totalSpent: "$11,050",
  },
];